### ISSUE TITLE
Cannot add more than one client

### ISSUE THREAD

**Issue by livenwee** [tatsuz0u/BitRemote#22]
你好开发者，为什么我测试版本中只能加入单个的下载工具配置，并无开发截图中的添加第二第三个配置的按钮，是哪里设置不对吗？不胜感激！
![IMG_5949](https://github.com/tatsuz0u/BitRemote/assets/22017770/a3b60fea-254c-40ea-86f3-a763e7ceb0b0)

**Comment by tatsuz0u** [comment]
您好，謝謝您的回報。
「新增用戶端」按鈕不被顯示出來是我們有意為之的，我們計畫在實作完 IAP（App 內購買）功能後為 TestFlight 用戶提供測試入口解鎖所有功能。
請留意後續更新。🙇

**Comment by tatsuz0u** [comment]
您好，我們現在提供了 Beta 試用解鎖功能，您可以使用它來添加更多用戶端了。

**Comment by FanxJK** [comment]
> 您好，我們現在提供了 Beta 試用解鎖功能，您可以使用它來添加更多用戶端了。

Mac 版还是只能添加一个吗？

**Comment by tatsuz0u** [comment]
> > 您好，我們現在提供了 Beta 試用解鎖功能，您可以使用它來添加更多用戶端了。
> 
> 
> 
> Mac 版还是只能添加一个吗？

Mac 版也可以使用試用解鎖功能解除用戶端數量限制，如果更新到最新版本後仍然看不到解鎖按鈕（一個沙漏圖示）的話就應該是 bug，屆時煩請回報問題給我們。

**Comment by FanxJK** [comment]
> > > 您好，我們現在提供了 Beta 試用解鎖功能，您可以使用它來添加更多用戶端了。
> > 
> > 
> > Mac 版还是只能添加一个吗？
> 
> Mac 版也可以使用試用解鎖功能解除用戶端數量限制，如果更新到最新版本後仍然看不到解鎖按鈕（一個沙漏圖示）的話就應該是 bug，屆時煩請回報問題給我們。

有一个沙漏图标，但是点击以后报错
<img width="1252" alt="image" src="https://github.com/BitRemote-Team/BitRemote/assets/22773968/a4411c5a-06f4-4f3a-9b14-4813ab568985">

**Comment by tatsuz0u** [comment]
@FanxJK 
謝謝您提供額外資訊，我們會嘗試修正這個問題。

**Comment by tatsuz0u** [comment]
@FanxJK 您好，build 58 應該修正了這個問題。
