### ISSUE TITLE
[BUG] Saving clients in multiple windows causes a crash

### ISSUE THREAD

**Issue by rxvincent** [tatsuz0u/BitRemote#31]
因为目前只能添加一个客户端,于是尝试绕过此限制,在没有添加任何客户端的情况下command+N可以打开一个新的窗口,分别添加客户端后重启应用, 会导致crash无法再次正常启动

**Comment by tatsuz0u** [comment]
您好，謝謝您的回報。

目前我們已經提供 Beta 試用解鎖功能，您可以使用它添加更多用戶端了。

但是根據您的描述，BitRemote 的確看起來在多窗口支援上存在問題，我們會進行進一步調查。

**Comment by tatsuz0u** [comment]
我們決定關閉設定上的多窗口支援，因為實際上並沒有支援它，這應該可以解決您提到的問題。
