### ISSUE TITLE
Response status code was unacceptable：405

### ISSUE THREAD

**Issue by ethanjtch** [tatsuz0u/BitRemote#34]
设置Transmission失败，但qBittorrent是成功的。

![IMG_2041](https://github.com/BitRemote-Team/BitRemote/assets/19629402/07f7b769-6224-47b7-a6fe-f601550b62e5)

**Comment by heddxh** [comment]
Same here

**Comment by hanshantao** [comment]
需要加上/transmission/rpc 路径

**Comment by tatsuzo-arkstudios** [comment]
> 需要加上/transmission/rpc 路径

@ethanjtch @heddxh 
感覺這個會有幫助。🤔

**Comment by heddxh** [comment]
确实加上就连上了，感觉可以关闭了？
感谢开发！

**Comment by tatsuzo-arkstudios** [comment]
謝謝，那我加上一個格式檢查吧。
