### ISSUE TITLE
「BUG」Display Issue with aria2 Task Names.

### ISSUE THREAD

**Issue by xielidun** [tatsuz0u/BitRemote#39]
Thank you very much to the developers for their hard work. This software is really useful to me, but I found that there is an issue with the task names not displaying properly in aria2 during use. I'm using a MacBook Pro 14-inch running version 13.6. I've encountered this bug on multiple servers, but it doesn't occur on the mobile version. Additionally, there's an intermittent crashing problem, although it doesn't currently affect usage.
![2](https://github.com/BitRemote-Team/BitRemote/assets/59214411/8e8634ca-573b-47bc-a8c6-b2ddbaaf5bfc)
![1](https://github.com/BitRemote-Team/BitRemote/assets/59214411/a52bf072-be47-4646-a4a5-fb6b3ebfe1e5)

**Comment by tatsuz0u** [comment]
Thanks for your detailed feedback.
We will look into this. 🤔

**Comment by tatsuzo-arkstudios** [comment]
Could you also please share the aria2 version? 🙏
