### ISSUE TITLE
About system compatibility issues

### ISSUE THREAD

**Issue by xielidun** [tatsuz0u/BitRemote#40]
Hello, sorry for the inconvenience again. According to the TestFlight prompt, there has been a change in software ownership, and at the same time, the required system update has also changed. The current system requirement is the latest macOS, but due to the stability needed for my work, I cannot update to the latest version of macOS. Would you consider expanding the range of supported systems? Thank you.

**Comment by tatsuz0u** [comment]
Thank you for reaching out and sharing your concerns. We understand the importance of stability in your work. However, after careful consideration, we have decided to continue supporting only the latest version of macOS for now.

We appreciate your understanding and are here to assist with any other questions you might have.
